### PR TITLE
Defer updates if tabs are suspended

### PR DESCRIPTION
**Pull request by deanoemcke**
It turns out that if you listen to the `onUpdateAvailable` event and do nothing when it fires, this prevents the extension from automatically updating. Instead it will wait until a browser restart before updating.
I believe this will be a major improvement to the update process for the extension.
Instead of suspended tabs suddenly disappearing and then reappearing after the update completes, and instead of a popup to warn the user what is about to happen, we can now simply delay the update until the user restarts their browser. 
During a browser restart, users will be much more amiable towards suspended tabs being recovered.

### CODE REVIEW

**Comment by ossilator** [comment]
the title of the MR is a bit of an understatement - this is the visible side effect of a somewhat more fundamental change - "defer updates if any tabs are suspended".

i don't really understand the last sentence - the update happens before chrome starts restoring the session, so the user shouldn't notice anything special in the first place, right? so what should they be more amiable towards then?

if this change proves to work as expected, the session manager can be thrown away, right?

**Comment by deanoemcke** [comment]
Thanks for the feedback. I have updated the PR title to reflect the real changes.
You are also correct in regards to the order of actions during a restart. Chrome updates the extension first, then tabs are restored. So there is no chance (i'm hesitant to say this) that any tabs will be lost.
I don't think this is cause the remove the session manager. There is still a chance that the extension can crash for whatever reason. Being able to recover from these situations is invaluable. Even simply refreshing the extension can do this. Besides, I believe that a lot of users have come to rely on the session manager for more than just tab recovery (for better or worse).

**Comment by deanoemcke** [comment]
It should also be noted that this code will only take effect AFTER the next update. So unfortunately, the next update will exhibit the same annoying pre-update behaviour as we have just experienced. Going forward from the though, we should have a much nicer update experience 🎉

**Comment by ossilator** [comment]
hmm, good point - session buddy runs uncoordinated with TGS, so it wouldn't know that it needs to preserve the state before the tabs evaporated. i suppose that's another thing that could be addressed by having the extensions talk to each other ...

**Pull request merged**
